#!/usr/bin/env python3

import asyncio
import random
import sys

from http import create_http_session
from imagefaplib import fetch_gallery

import config

def shuffled_proxies():
    return random.sample(config.proxies, k=len(config.proxies))

async def main():

    if len(sys.argv) <= 1:
        print('Please provide gallery URL')
        return

    async with create_http_session(proxies=shuffled_proxies(), **config.http) as session:
        for url in sys.argv[1:]:
            await fetch_gallery(session, url)


asyncio.run(main())
